- lib/lita.rb
- lib/lita/handler/chat_router.rb
- lib/lita/http_callback.rb
- spec/lita/handler/chat_router_spec.rb
- spec/lita/handler/http_router_spec.rb
The use case is to report exceptions that happen in production to error tracking services (errbit / airbrake / bugsnag / sentry).
The API is as simple as assigning a Proc to `Lita.error_handler`:
```ruby
Lita.error_handler = lambda do |error|
Airbrake.notify(error)
end
```
@jimmycuadra what do you think of this?
cc @sirupsen
> Allow to register a error handler

- lib/lita/rspec/handler.rb
- spec/lita/rspec/handler_spec.rb
This adds a `base_handlers` property that is available when describing an rspec test. Uses a list assuming multiple possible required handlers. This fixes issue #84
> Add ability to set base handlers

- lib/lita/user.rb
- spec/lita/user_spec.rb
When implementing `#==` an object should also implement `#hash` so that
objects correctly hash for storage in data structures like Hash. In the
same vein, `#eql?` should also be implemented as it is used by Hash and
other data structures to check for member equality.
> Fully implement User equality and hashing

- templates/plugin/gemspec.tt
Following semver where the 3rd digit is a patch, you can't have a patch on nothing so the lowest version number is 0.1.0.
> initial plugin version 0.1.0

- lib/lita/adapters/shell.rb
- spec/lita/adapters/shell_spec.rb
I would like to have it so that when you are running in shell it looks like the source of a response is coming from a chat room. This is in line with how hubut works as well when running in shell.
> making the shell adapter source have a room called 'shell_room'

- lib/lita.rb
- lib/lita/config.rb
- lib/lita/default_configuration.rb
- lib/lita/logger.rb
Made it so that you can pass in a proc to the logger and it will use that as the log formatting to accomodate people who want specific log formatting.
I did this because we are deploying our implementation of Lita at Spiceworks and we wanted to change the logger formatting. I have monkey patched this for now but I figured other people may want to be able to format their loggers without having to monkey patch lita so I made a PR to implement it.
> Allow the logging formatting to be configurable.

- .travis.yml
I think we should support multiple versions of ruby in case users have reasons
for 2.0 v. 2.1 v. 2.2 so I added the stable builds from each of these in the
travis configs so that the test suite will run against all of these.
If you only want to test against 2.0 that's fine, just close this. If you want to test against multiple versions of ruby then merge away!
> adding ruby versions to the travis.yml.

- lib/lita/robot.rb
We need to move the persisted rooms command on the robot to not be private.
Otherwise the adapters can't access the list of persisted rooms and therefore
can't recconect to them on start up.
> Move persisted_rooms to not be private.

- lib/lita/rspec/handler.rb
- spec/lita/rspec_spec.rb
Allows developers to write specs that have users sending messages directly to the bot or from a room. Makes it easier to test private and public messages.
> allow user to send message from a room in tests

- lib/lita/message.rb
- lib/lita/response.rb
- spec/lita/message_spec.rb
- spec/lita/response_spec.rb
Currently you can retrieve the user object from a response in your
handler with
```ruby
user = response.user
```
This is how you retrieve a room object before/after this commit
```ruby
room = response.message.source.room_object
room = response.room_object
```
This better demonstrates the symmetry between a user object and a room
object.
> get the room object from the response

- lib/lita/message.rb
- lib/lita/response.rb
- spec/lita/message_spec.rb
- spec/lita/response_spec.rb
Provides an easier alternative into checking whether the response is a
private message, e.g.:
```ruby
response.message.source.private_message?
response.private_message?
```
This resolves issue #123
> Can now check whether a response is a private message

- templates/plugin/lib/lita/plugin_type/plugin.tt
This way the registration survives constant name changes (which is of course a problem I just had 😖).
> Use self instead of repeating the constant name

- lib/lita/handler/chat_router.rb
- spec/lita/handler/chat_router_spec.rb
This makes a payload containing the handler name, route, message, and robot accessible by a handler whenever a message is dispatched.
> Trigger :message_dispatched event in ChatRouter#dispatch

- lib/lita/rspec/handler.rb
- spec/lita/rspec_spec.rb
This adds the ability to send private messages and commands within a
handler's test suite.
> Add privately parameter to send_message and send_command

- templates/plugin/README.tt
Noticed that the template still uses PNG images when creating a new plugin just today, see https://github.com/nTraum/lita-down/commit/4b9ea18d5134ae5dc1238bf5091c6dec586286b8.
> Use SVG badges for coveralls and Travis CI

- templates/robot/lita_config.rb
As mentioned in [Lita 4.0 release notes](http://docs.lita.io/releases/4/).
> The redis configuration attribute is now a hash. Lita 4 will continue to support struct-style access, but only hash-style access will be supported in Lita 5, so you should update now.
> Use new hash-style access for Redis in robot config template

- templates/plugin/gemspec.tt
Since it has a C-extension.
So don't require it when run on JRuby.
> byebug won't work on JRuby

- lita.gemspec
- spec/spec_helper.rb
- templates/plugin/spec/spec_helper.tt
In https://github.com/colszowka/simplecov/pull/317 Simplecov changed how they specify multiple formatters.  This change updates to the newer syntax.
> Update Simplecov formatter syntax

- lib/lita/message.rb
- spec/lita/message_spec.rb
Includes some basic tests, rdoc comments, and a version bump.
Proposing this implementation of functionality to allow for [lita-slack#73 (Add a reaction to a message)](https://github.com/kenjij/lita-slack/issues/73), which requires Slack specific data provided to the adapter.
> Allow adapters to attach data to Lita::Message

- lib/lita/source.rb
- spec/lita/source_spec.rb
Rather than just initializing a room object, this will ensure the room belonging to a message `Source` is fetching from the database. This provides access to room metadata that you would otherwise have to look up after the fact.
See discussion https://github.com/litaio/lita/commit/f507bb0b02940b35b1d9ce3218714a0a5046c460#commitcomment-15466157
cc @jimmycuadra
> Fetch room data in message source

- templates/plugin/gitignore
Ignore lita_config.rb, when developing plugin.
> Add lita_config.rb to gitignore

- lib/lita/message.rb
- spec/lita/message_spec.rb
The previous regex allowed each line beginning with Lita's mention name
or alias in a multi-line message to be interpreted as a command, which
is problematic for commands deliberately enclosed in code blockquotes
like "```\n!foo\n```". With this change, Lita will check for the
presence of a command once per message instead of once per line.
> Modify regex used by the Message class to detect a command

- lib/lita/robot.rb
- spec/lita/handler/chat_router_spec.rb
Certain handlers use the chat route regex `/./` to permissively trigger
a method and evaluate some sort of conditional logic therein. This
effectively means that `:unhandled_message` is never triggered, which
breaks functionality like invalid command logging in lita-metrics. With
this change, plugin authors will no longer have to use the permissive
regex as a workaround. Please see the following for an example:
https://github.com/tristaneuan/lita-google-translate/pull/1
> Trigger :message_received whenever robot.receive is called

- lib/lita.rb
- lib/lita/cli.rb
- spec/lita_spec.rb
This will add a special command that will do most of the boot-up process
except it will not "run", but exit back to the shell.
If there are any issues with your configuration, it will fail exactly
like when you execute with `lita start`.
The motivation came from the need to check before deploy, so I can automate a few things on my workflow. This will also be a good fit for docker images or anything that does continuous deployment.
If you need any change or additional documentation, please ping me.
> Added a `validate` CLI command to load an test config for scripting

- lib/lita/http_callback.rb
This fixes the following error which masks the real cause of an exception being raised:
```
Puma caught this error: undefined local variable or method `error' for #<Lita::HTTPCallback:0x0055f3419a0c10> (NameError)
/artifacts/ruby/2.3.0/bundler/gems/lita-63c0aea70420/lib/lita/http_callback.rb:34:in `rescue in call'
/artifacts/ruby/2.3.0/bundler/gems/lita-63c0aea70420/lib/lita/http_callback.rb:23:in `call'
/artifacts/ruby/2.3.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
(eval):567:in `call'
/artifacts/ruby/2.3.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
/artifacts/ruby/2.3.0/bundler/gems/lita-63c0aea70420/lib/lita/rack_app.rb:46:in `call'
/artifacts/ruby/2.3.0/gems/newrelic_rpm-3.18.0.329/lib/new_relic/agent/instrumentation/middleware_trac …
```
> Fix error variable name in http_callback.rb

- lib/lita.rb
- lib/lita/default_configuration.rb
- lib/lita/registry.rb
- lib/lita/rspec.rb
- spec/lita/default_configuration_spec.rb
* move the `REDIS_NAMESPACE` constant into `Lita::DefaultConfiguration`
* expose `config.robot.redis_namespace` and use the new constant's value as its default
Fixes: #228
> make Redis namespace configurable
